In [38]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.metrics import roc_curve, auc, confusion_matrix
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt

In [99]:
# read in X and Y dataframes
X = pd.read_csv('X.csv',index_col=0)
Y = pd.read_csv('Y.csv',index_col=0)

In [47]:
X

,2315633,2315739,2316245,2317434,2317512,2318086,2318257,2318455,2318656,2319252,...,4049862,4051723,4053085,4054204,4054414,4054427,4054437,4054639,4055661,7385641
GSM547265,6.63426,6.61106,8.11258,8.16793,6.20079,6.63915,6.89326,5.62877,6.09928,6.47993,...,8.18693,6.86065,5.94963,7.10436,5.75385,6.05586,6.01827,8.13807,9.588890,5.29320
GSM547266,6.77339,6.92113,8.32914,8.51536,6.22947,6.76890,7.32080,4.75461,6.23427,6.76784,...,8.00690,7.22674,6.19202,7.25671,5.08699,5.06429,5.19170,7.83636,10.689400,5.60921
GSM547267,6.82841,6.89531,7.93158,8.02643,6.74113,7.00569,6.87472,4.72446,5.87781,6.50739,...,7.64298,7.30349,6.51488,6.79476,5.62140,5.33508,6.24613,8.30760,9.839500,5.93616
GSM547268,6.12285,6.44312,7.95581,8.58608,6.15481,7.17477,6.65657,4.61109,6.40874,6.65112,...,7.45939,7.31671,6.77977,8.21227,4.49934,5.16386,4.57206,8.05844,10.982200,5.47754
GSM547269,6.63802,6.33454,8.12448,8.52964,5.89551,6.25038,6.35403,5.08841,6.89595,6.24782,...,8.02464,6.65667,5.40819,6.92056,5.54521,5.56643,5.62098,8.12339,10.314700,4.85305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM881206,6.53000,6.78000,7.82000,9.11000,5.97000,6.49000,7.60000,4.49000,7.02000,7.08000,...,8.05000,7.57000,7.37000,8.65000,5.05000,4.79000,4.62000,8.28000,11.026980,5.29000
GSM881207,6.77000,7.19000,8.33000,9.05000,6.27000,6.78000,7.62000,4.74000,6.30000,6.98000,...,8.03000,7.87000,6.58000,11.24000,5.81000,6.39000,7.01000,8.87000,9.186072,5.27000
GSM881208,6.53000,6.74000,8.25000,9.11000,6.35000,6.89000,7.53000,4.36000,6.84000,7.17000,...,8.02000,7.77000,6.09000,6.62000,5.30000,5.09000,4.94000,8.57000,10.624360,5.32000
GSM881209,6.62000,6.91000,8.19000,9.10000,6.38000,6.30000,7.32000,4.99000,6.23000,6.85000,...,8.56000,7.16000,5.75000,7.01000,5.86000,5.31000,5.17000,8.99000,9.842080,4.91000
GSM881210,6.62000,6.89000,8.56000,9.13000,6.18000,7.11000,7.58000,4.37000,8.29000,7.22000,...,7.98000,7.86000,5.95000,6.40000,5.19000,4.50000,4.48000,8.68000,10.893260,5.74000

In [48]:
Y

    status
0        0
1        1
2        0
3        1
4        0
..     ...
87       1
88       0
89       1
90       0
91       1

[92 rows x 1 columns]

In [100]:
# store gene IDs before applying feature selection
gene_ids = X.columns.tolist()
# Convert dataframes to numpy arrays
X = X.values
Y = Y.values.ravel()

In [50]:
X

array([[ 6.63426,  6.61106,  8.11258, ...,  8.13807,  9.58889,  5.2932 ],
       [ 6.77339,  6.92113,  8.32914, ...,  7.83636, 10.6894 ,  5.60921],
       [ 6.82841,  6.89531,  7.93158, ...,  8.3076 ,  9.8395 ,  5.93616],
       ...,
       [ 6.53   ,  6.74   ,  8.25   , ...,  8.57   , 10.62436,  5.32   ],
       [ 6.62   ,  6.91   ,  8.19   , ...,  8.99   ,  9.84208,  4.91   ],
       [ 6.62   ,  6.89   ,  8.56   , ...,  8.68   , 10.89326,  5.74   ]])

In [51]:
Y

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1], dtype=int64)

In [176]:
# Feature selection using variance threshold
selector = VarianceThreshold(threshold=1.2)

In [177]:
X_selected = selector.fit_transform(X)

 the Variance Threshold feature selection is performed using the VarianceThreshold() function from scikit-learn. The fit_transform() method of this selector is applied to the input data X to obtain the selected features in X_selected.

In [178]:
# store selected gene IDs
selected_gene_ids = np.array(gene_ids)[selector.get_support()].tolist()

In [94]:
# Split data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_selected, Y, test_size=0.2, random_state=42)

The code then splits the data into training and testing sets using train_test_split(). 
test_size is a parameter that specifies the proportion of the dataset to include in the test set. For example, if test_size is set to 0.2, then 20% of the data will be used for testing and the remaining 80% will be used for training.

random_state is a parameter that controls the random seed used by the train-test split function. Setting a value for random_state ensures that the train-test split is reproducible, i.e., if you run the code with the same random_state value multiple times, you will get the same train-test split every time. If you don't set a value for random_state, the train-test split will be different every time you run the code.

In [95]:
# Train a logistic regression model
model = LogisticRegression(max_iter=1000)
kfold = 5
scores = cross_val_score(model, X_train, Y_train, cv=kfold)
print(f'Cross-validation score: {np.mean(scores)}')

Cross-validation score: 0.959047619047619

In [179]:
print(len(selected_gene_ids))

169

In [180]:
selected_gene_ids = [int(x) for x in selected_gene_ids]
type(selected_gene_ids[0])

int

In [181]:
# Export the list to csv file
import csv
with open('gene_ids_from_algo1.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    for value in zip(selected_gene_ids):
        writer.writerow(value)